name = "Kabsch"
uuid = "f04b186e-52d5-4f75-9fe8-bf69181293d4"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
KabschCUDAExt = "CUDA"
KabschStaticArraysExt = "StaticArrays"

[compat]
CUDA = "5"
Compat = "4.16.0"
LinearAlgebra = "1"
NNlib = "0.9"
StaticArrays = "1"
Statistics = "1"
julia = "1.10"
